# src/sequencing/splitter.py

# Purpose: Defines the DatasetSplitter class, which provides methods for 
# splitting a list of Sequence objects into training, validation, and test sets.
# The splitter supports two strategies: stratified random splitting by label 
# and chronological splitting based on sequence ID ordering.

# Input: - A list of Sequence objects, where each Sequence has an optional label 
#          and a sequence ID that may encode time order.
#        - The desired ratios for validation and test sets, and a random seed for reproducibility.

# Output: - The split_stratified method returns three lists of Sequence objects for 
#           training, validation, and test sets, ensuring that the label distribution is preserved.
#         - The split_time_based method returns three lists of Sequence objects for 
#           training, validation, and test sets based on chronological order.

# Used by: - The main application to split the sequences generated by the sequence builders into training, 
#            validation, and test sets for model training and evaluation.

"""Stage 3 — Sequencing: train/val/test splitter."""
from __future__ import annotations

import random
from collections import defaultdict
from typing import Optional, Tuple

from .models import Sequence


class DatasetSplitter:
    """
    Splits a list of Sequence objects into train / val / test subsets.

    Two strategies are supported:

    * split_stratified  – random stratified split by label (default).
    * split_time_based  – chronological split using sequence_id ordering
                          (assumes sequence IDs encode time order, e.g.
                          window_0, window_10, … or integer session_ids).

    Parameters
    ----------
    val_ratio  : fraction of data for validation (default 0.10)
    test_ratio : fraction of data for test       (default 0.10)
    seed       : random seed for reproducibility (default 42)
    """

    def __init__(self,
                 val_ratio: float = 0.10,
                 test_ratio: float = 0.10,
                 seed: int = 42):
        if val_ratio + test_ratio >= 1.0:
            raise ValueError("val_ratio + test_ratio must be < 1.0")
        self.val_ratio = val_ratio
        self.test_ratio = test_ratio
        self.seed = seed

    # ------------------------------------------------------------------
    def split_stratified(
        self,
        sequences: list[Sequence],
    ) -> Tuple[list[Sequence], list[Sequence], list[Sequence]]:
        """
        Stratified random split that preserves label distribution.

        Returns (train, val, test).
        """
        rng = random.Random(self.seed)

        # Group by label (None treated as a separate class)
        buckets: dict[Optional[int], list[Sequence]] = defaultdict(list)
        for seq in sequences:
            buckets[seq.label].append(seq)

        train, val, test = [], [], []
        for label, seqs in buckets.items():
            shuffled = seqs[:]
            rng.shuffle(shuffled)
            n = len(shuffled)
            n_test = max(1, round(n * self.test_ratio))
            n_val  = max(1, round(n * self.val_ratio))
            test  += shuffled[:n_test]
            val   += shuffled[n_test:n_test + n_val]
            train += shuffled[n_test + n_val:]

        return train, val, test

    # ------------------------------------------------------------------
    def split_time_based(
        self,
        sequences: list[Sequence],
    ) -> Tuple[list[Sequence], list[Sequence], list[Sequence]]:
        """
        Chronological split: first (1-val-test)% → train,
        next val% → val, last test% → test.

        The ordering of `sequences` is assumed to reflect time.
        If sequences come from a sliding-window builder they are already
        ordered; session-based sequences are taken as-is.
        """
        n = len(sequences)
        n_test = max(1, round(n * self.test_ratio))
        n_val  = max(1, round(n * self.val_ratio))
        n_train = n - n_val - n_test

        train = sequences[:n_train]
        val   = sequences[n_train:n_train + n_val]
        test  = sequences[n_train + n_val:]
        return train, val, test
