# scripts/run_0_4.py

# Purpose: This script serves as a one-command pipeline to run stages 01 through 04B of the anomaly detection in log data project.
# It allows users to execute the entire pipeline or specific stages with optional modes for faster execution (e.g., demo mode).
# The script also provides an option to skip the transformer stage,
# which can be useful for users running on CPU-only machines.

# Input: Command-line arguments specifying the mode, stages to run, and device for the transformer.

# Output: Logs indicating the progress and completion of each stage, along with any results generated by the stages.

# Used by: This script is used by anyone who wants to run the anomaly detection pipeline from stages 01 to 04B in a streamlined manner.

"""
One-command pipeline: Stages 01 through 04B.

Usage:
    python scripts/run_0_4.py               # full pipeline
    python scripts/run_0_4.py --mode demo   # fast smoke-test (~1 min)
    python scripts/run_0_4.py --mode demo --skip-transformer
    python scripts/run_0_4.py --stages 01 02 03   # run only specific stages
"""
import argparse
import importlib
import logging
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

STAGE_MODULES = {
    "01": "scripts.stage_01_data",
    "02": "scripts.stage_02_templates",
    "03": "scripts.stage_03_sequences",
    "04a": "scripts.stage_04_baseline",
    "04b": "scripts.stage_04_transformer",
}


def run_stage(module_path: str, mode: str, **kwargs) -> None:
    # Import the script module and call its main()
    import importlib.util, types
    rel_path = module_path.replace(".", "/") + ".py"
    spec = importlib.util.spec_from_file_location(
        module_path,
        ROOT / rel_path,
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    # Pass extra kwargs (e.g. device for transformer)
    sig_params = mod.main.__code__.co_varnames[:mod.main.__code__.co_argcount]
    call_kwargs = {"mode": mode}
    for k, v in kwargs.items():
        if k in sig_params:
            call_kwargs[k] = v
    mod.main(**call_kwargs)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run stages 01-04 pipeline")
    parser.add_argument("--mode", default="full", choices=["full", "demo"],
                        help="'demo' runs fast with small data subset")
    parser.add_argument("--skip-transformer", action="store_true",
                        help="Skip stage 04B (transformer) — useful on CPU-only machines")
    parser.add_argument("--device", default="cpu",
                        help="Torch device for transformer (cpu | cuda)")
    parser.add_argument("--stages", nargs="+", default=None,
                        metavar="STAGE",
                        help="Run only these stages (e.g. --stages 01 02)")
    args = parser.parse_args()

    stages_to_run = args.stages or (
        ["01", "02", "03", "04a"] +
        ([] if args.skip_transformer else ["04b"])
    )

    log.info("=" * 60)
    log.info("Pipeline run_0_4 | mode=%s | stages=%s", args.mode, stages_to_run)
    log.info("=" * 60)

    t_total = time.time()
    for stage_id in stages_to_run:
        key = stage_id.lower()
        if key not in STAGE_MODULES:
            log.error("Unknown stage: %s. Valid: %s", stage_id,
                      list(STAGE_MODULES.keys()))
            sys.exit(1)

        log.info("-" * 40)
        log.info("Running stage %s ...", stage_id)
        t_stage = time.time()

        module_path = STAGE_MODULES[key]
        extra = {"device": args.device} if key == "04b" else {}
        run_stage(module_path, mode=args.mode, **extra)

        log.info("Stage %s done in %.1fs", stage_id, time.time() - t_stage)

    log.info("=" * 60)
    log.info("All stages complete in %.1fs", time.time() - t_total)
    log.info("=" * 60)


if __name__ == "__main__":
    main()
