# scripts/stage_01_synth_validate.py

# Purpose: Validate the synthetic dataset generated by stage_01_synth_generate.py. 
# Checks schema, label distribution, and phase coverage, 
# then writes a markdown report to reports/stage_30_synthetic_data_report.md.

# Input: Path to the synthetic data directory (default: data/synth/), 
# which should contain events_synth.csv and optionally scenarios.json.

# Output: A markdown report at reports/stage_30_synthetic_data_report.md summarizing the validation results, 
# dataset statistics, and example messages. Logs are written to ai_workspace/logs/stage_01_synth_validate.log.

# Used by: This script can be run independently to validate the synthetic dataset. 
# It is not directly used by other scripts but provides a report that can be referenced 
# when using the synthetic data in stages 1–5 of the anomaly detection pipeline.

"""
Stage 01 — Synthetic: validate generated outputs.

Loads data/synth/ outputs, checks schema, label distribution, and phase
coverage, then writes:
  reports/stage_30_synthetic_data_report.md

Logs to: ai_workspace/logs/stage_01_synth_validate.log

Usage:
    python scripts/stage_01_synth_validate.py
    python scripts/stage_01_synth_validate.py --indir data/synth
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import pandas as pd

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOG_DIR     = ROOT / "ai_workspace" / "logs"
REPORTS_DIR = ROOT / "reports"
LOG_DIR.mkdir(parents=True,     exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

_log_path = LOG_DIR / "stage_01_synth_validate.log"
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.FileHandler(_log_path, encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger(__name__)

REQUIRED_COLUMNS = {"timestamp", "service", "level", "message",
                    "session_id", "label"}
META_COLUMNS     = {"host", "component", "scenario_id", "phase"}
ALL_PHASES       = {"normal", "degradation", "failure"}

REPORT_PATH = REPORTS_DIR / "stage_30_synthetic_data_report.md"


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def _check_required_columns(df: pd.DataFrame, name: str) -> list[str]:
    missing = REQUIRED_COLUMNS - set(df.columns)
    if missing:
        return [f"[FAIL] {name}: missing required columns: {sorted(missing)}"]
    return [f"[PASS] {name}: all required columns present"]


def _check_meta_columns(df: pd.DataFrame, name: str) -> list[str]:
    missing = META_COLUMNS - set(df.columns)
    if missing:
        return [f"[WARN] {name}: missing meta columns: {sorted(missing)} "
                f"(expected for synthetic data)"]
    return [f"[PASS] {name}: all meta columns present"]


def _check_label_distribution(df: pd.DataFrame, name: str) -> list[str]:
    msgs = []
    if "label" not in df.columns:
        return [f"[FAIL] {name}: 'label' column missing"]
    vc = df["label"].value_counts().sort_index().to_dict()
    if 0 not in vc:
        msgs.append(f"[FAIL] {name}: no label=0 (normal) events found")
    else:
        msgs.append(f"[PASS] {name}: label=0 count={vc.get(0, 0):,}")
    if 1 not in vc:
        msgs.append(f"[FAIL] {name}: no label=1 (anomaly) events found")
    else:
        msgs.append(f"[PASS] {name}: label=1 count={vc.get(1, 0):,}")
    return msgs


def _check_phase_distribution(df: pd.DataFrame, name: str) -> list[str]:
    if "phase" not in df.columns:
        return [f"[WARN] {name}: 'phase' column missing"]
    phases_found = set(df["phase"].dropna().unique())
    missing = ALL_PHASES - phases_found
    extra   = phases_found - ALL_PHASES
    msgs = []
    if missing:
        msgs.append(f"[FAIL] {name}: missing phases: {sorted(missing)}")
    else:
        msgs.append(f"[PASS] {name}: all three phases present")
    if extra:
        msgs.append(f"[WARN] {name}: unexpected phase values: {sorted(extra)}")
    return msgs


def _check_messages(df: pd.DataFrame, name: str) -> list[str]:
    if "message" not in df.columns:
        return [f"[FAIL] {name}: 'message' column missing"]
    empty = (df["message"].isna() | (df["message"].str.strip() == "")).sum()
    if empty:
        return [f"[FAIL] {name}: {empty:,} empty messages found"]
    return [f"[PASS] {name}: all messages non-empty ({len(df):,} rows)"]


def _check_label_dtype(df: pd.DataFrame, name: str) -> list[str]:
    if "label" not in df.columns:
        return []
    dt = df["label"].dtype
    if not pd.api.types.is_integer_dtype(dt):
        return [f"[FAIL] {name}: label dtype is {dt}, expected integer"]
    return [f"[PASS] {name}: label dtype={dt}"]


# ---------------------------------------------------------------------------
# Main validate function
# ---------------------------------------------------------------------------

def run_validate(indir: Path) -> dict:
    log.info("=== Stage 01 Synthetic Validate ===")
    log.info("Input dir: %s", indir)
    t_start = time.perf_counter()

    checks: list[str] = []
    fails  = 0

    # ------------------------------------------------------------------
    # Load CSV
    # ------------------------------------------------------------------
    csv_path = indir / "events_synth.csv"
    if not csv_path.exists():
        log.error("events_synth.csv not found at %s — run stage_01_synth_generate.py first",
                  csv_path)
        sys.exit(1)

    log.info("Loading %s ...", csv_path)
    df = pd.read_csv(csv_path)
    log.info("Loaded %d rows, %d columns", len(df), len(df.columns))

    # ------------------------------------------------------------------
    # Run checks
    # ------------------------------------------------------------------
    for check_fn in [
        _check_required_columns,
        _check_meta_columns,
        _check_label_distribution,
        _check_phase_distribution,
        _check_messages,
        _check_label_dtype,
    ]:
        results = check_fn(df, "events_synth.csv")
        checks.extend(results)
        for r in results:
            if r.startswith("[FAIL]"):
                fails += 1
                log.error(r)
            elif r.startswith("[WARN]"):
                log.warning(r)
            else:
                log.info(r)

    # ------------------------------------------------------------------
    # Scenarios JSON
    # ------------------------------------------------------------------
    scen_path = indir / "scenarios.json"
    if scen_path.exists():
        with open(scen_path, encoding="utf-8") as fh:
            scenarios = json.load(fh)
        checks.append(f"[PASS] scenarios.json loaded: {len(scenarios)} scenarios")
        log.info("Loaded %d scenarios from scenarios.json", len(scenarios))
    else:
        checks.append("[WARN] scenarios.json not found")
        log.warning("scenarios.json not found")
        scenarios = []

    # ------------------------------------------------------------------
    # Compute statistics for report
    # ------------------------------------------------------------------
    label_counts  = df["label"].value_counts().sort_index().to_dict()
    phase_counts  = df["phase"].value_counts().sort_index().to_dict() if "phase" in df.columns else {}
    service_counts = df["service"].value_counts().to_dict() if "service" in df.columns else {}
    anomaly_rate  = float(df["label"].mean() * 100)

    log.info("Anomaly rate: %.2f%%", anomaly_rate)
    log.info("Phase counts: %s", phase_counts)
    log.info("Service counts: %s", service_counts)

    # ------------------------------------------------------------------
    # Sample messages per pattern
    # ------------------------------------------------------------------
    sample_msgs: dict[str, list[str]] = {}
    if "scenario_id" in df.columns:
        for scid in df["scenario_id"].unique():
            sub = df[df["scenario_id"] == scid]
            sample_msgs[scid] = sub["message"].head(3).tolist()

    # ------------------------------------------------------------------
    # Write report
    # ------------------------------------------------------------------
    elapsed = time.perf_counter() - t_start
    _write_report(
        df=df,
        scenarios=scenarios,
        checks=checks,
        label_counts=label_counts,
        phase_counts=phase_counts,
        service_counts=service_counts,
        anomaly_rate=anomaly_rate,
        sample_msgs=sample_msgs,
        csv_path=csv_path,
        elapsed=elapsed,
    )

    status = "PASS" if fails == 0 else f"FAIL ({fails} failures)"
    log.info("Validation status: %s", status)
    log.info("Report written: %s", REPORT_PATH)
    log.info("=== Stage 01 Synthetic Validate complete in %.2fs ===", elapsed)

    return {
        "n_rows":       len(df),
        "n_failures":   fails,
        "anomaly_rate": round(anomaly_rate, 2),
        "status":       status,
    }


# ---------------------------------------------------------------------------
# Report writer
# ---------------------------------------------------------------------------

def _write_report(
    df: pd.DataFrame,
    scenarios: list[dict],
    checks: list[str],
    label_counts: dict,
    phase_counts: dict,
    service_counts: dict,
    anomaly_rate: float,
    sample_msgs: dict,
    csv_path: Path,
    elapsed: float,
) -> None:
    n_normal = label_counts.get(0, 0)
    n_anomaly = label_counts.get(1, 0)
    n_total   = n_normal + n_anomaly

    lines = [
        "# Stage 30 — Synthetic Data Report",
        "",
        "**Generated by:** `scripts/stage_01_synth_validate.py`  ",
        f"**Source file:** `{csv_path.relative_to(ROOT)}`  ",
        f"**Total events:** {n_total:,}  ",
        f"**Anomaly rate:** {anomaly_rate:.2f}%  ",
        "",
        "---",
        "",
        "## 1. Executive Summary",
        "",
        f"The synthetic subsystem generated **{n_total:,}** log events across "
        f"**{len(scenarios)}** scenarios, covering four failure pattern types:",
        "",
        "| Pattern | Description |",
        "|---------|-------------|",
        "| `memory_leak` | Heap grows until process is OOM-killed |",
        "| `disk_full` | /var/data fills until writes are blocked |",
        "| `auth_brute_force` | Login failures escalate to account lockouts |",
        "| `network_flap` | eth0 latency/loss grows until interface goes down |",
        "",
        "Each scenario runs through three phases: **normal** (60%), "
        "**degradation** (30%), **failure** (10%) by default. "
        "A fifth *hybrid* scenario interleaves all four patterns.",
        "",
        "Events are schema-compatible with `KaggleDatasetLoader.normalize_schema()` "
        "and can be fed directly into the Stage 1–5 pipeline.",
        "",
        "---",
        "",
        "## 2. Scenarios Table",
        "",
        "| scenario_id | service | host | pattern(s) | n_events | anomaly_rate |",
        "|-------------|---------|------|------------|----------|-------------|",
    ]

    for sc in scenarios:
        patterns = (sc.get("pattern_names") or [sc.get("pattern_name", "?")])
        p_str = ", ".join(patterns)
        lines.append(
            f"| {sc.get('scenario_id','?')} "
            f"| {sc.get('service','?')} "
            f"| {sc.get('host','?')} "
            f"| {p_str} "
            f"| {sc.get('n_events',0):,} "
            f"| {sc.get('anomaly_rate',0)*100:.1f}% |"
        )

    lines += [
        "",
        "---",
        "",
        "## 3. Label Distribution",
        "",
        f"| label | count | pct |",
        f"|-------|------:|----:|",
        f"| 0 (normal)  | {n_normal:,} | {n_normal/n_total*100:.1f}% |",
        f"| 1 (anomaly) | {n_anomaly:,} | {n_anomaly/n_total*100:.1f}% |",
        f"| **total**   | {n_total:,} | 100.0% |",
        "",
        "**Phase breakdown:**",
        "",
        "| phase | events |",
        "|-------|-------:|",
    ]
    for ph, cnt in sorted(phase_counts.items()):
        lines.append(f"| {ph} | {cnt:,} |")

    lines += [
        "",
        "---",
        "",
        "## 4. Example Messages (per scenario)",
        "",
    ]
    for scid, msgs in sample_msgs.items():
        lines.append(f"**{scid}:**")
        lines.append("```")
        for m in msgs:
            lines.append(m)
        lines.append("```")
        lines.append("")

    lines += [
        "---",
        "",
        "## 5. How to Regenerate",
        "",
        "```powershell",
        "# Install dependencies",
        "pip install -r requirements.txt",
        "",
        "# Demo run (20,000 events, fast)",
        "python scripts/stage_01_synth_generate.py --mode demo",
        "",
        "# Validate outputs",
        "python scripts/stage_01_synth_validate.py",
        "",
        "# Full run (200,000 events)",
        "python scripts/stage_01_synth_generate.py --mode full --events 200000",
        "",
        "# Custom seed",
        "python scripts/stage_01_synth_generate.py --mode demo --seed 123",
        "```",
        "",
        "---",
        "",
        "## 6. Integration with Existing Pipeline (Stages 1–5)",
        "",
        "The synthetic DataFrame matches the `normalize_schema()` output of",
        "`KaggleDatasetLoader`, so it can be used as a drop-in replacement or",
        "mixed with real data:",
        "",
        "```python",
        "from src.synthetic import SyntheticLogGenerator",
        "from src.synthetic import MemoryLeakPattern, ScenarioBuilder",
        "",
        "builder   = ScenarioBuilder()",
        "generator = SyntheticLogGenerator([MemoryLeakPattern()], seed=42)",
        "scenario  = builder.build_scenario(",
        "    scenario_id='mem_test', service='app', host='h1',",
        "    start_ts=1704067200.0, n_events=1000,",
        "    pattern_name='memory_leak'",
        ")",
        "events = generator.generate(1000, scenario)",
        "df     = SyntheticLogGenerator.events_to_dataframe(events)",
        "# df columns: timestamp, service, level, message, session_id, label, ...",
        "```",
        "",
        "**Stage 5 runtime:** synthetic events can be fed directly to",
        "`InferenceEngine.ingest()` since they carry `token_id` in meta if",
        "you add tokenization (via `EventTokenizer`) beforehand.",
        "",
        "**Session IDs:** each 50-event window forms one session",
        "(`{scenario_id}_s{t//50}`), matching Stage 5 window_size=50.",
        "",
        "---",
        "",
        "## 7. Known Limitations",
        "",
        "1. **No real templates**: synthetic messages are not drawn from",
        "   `artifacts/templates.json`. Running them through `TemplateMiner`",
        "   will create new template IDs not seen by the trained models.",
        "",
        "2. **Label ramp**: the degradation phase is labeled 100% anomalous",
        "   from event 1. In real scenarios, degradation starts subtly.",
        "   A finer label scheme (e.g., ramp based on metric threshold) can",
        "   be implemented by overriding `label_for_event()` in each pattern.",
        "",
        "3. **No multi-host correlation**: each scenario runs on one host.",
        "   Distributed failure scenarios (e.g., cascading across hosts) are",
        "   not yet modelled.",
        "",
        "4. **Baseline model not re-trained**: the existing `models/baseline.pkl`",
        "   and `models/transformer.pt` were trained on HDFS/BGL data.",
        "   For accurate anomaly detection on synthetic events, re-run",
        "   Stages 3–4 including synthetic data in the training set.",
        "",
        "---",
        "",
        "## Validation Results",
        "",
        "| Check | Result |",
        "|-------|--------|",
    ]
    for c in checks:
        tag = c.split("]")[0].lstrip("[")
        msg = c.split("]", 1)[1].strip()
        lines.append(f"| {tag} | {msg} |")

    lines += [
        "",
        "---",
        "",
        f"_Generated by stage_01_synth_validate.py in {elapsed:.1f}s_",
    ]

    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Stage 01 Synthetic Validate")
    parser.add_argument("--indir", type=Path,
                        default=ROOT / "data" / "synth")
    args = parser.parse_args()
    run_validate(args.indir)


if __name__ == "__main__":
    main()
